<b>Исключения в конструкторах и деструкторах</b>

Исключения в конструкторах
Помимо ситуации, когда уже невозможно создать объект с помощью операции *new* и генерируется исключение типа *bad_alloc*, случается так, что исключение происходит при создании объекта, то есть внутри конструктора объекта. Так как в C++ конструктор не возвращает никакого значения, исключения представляются единственным способом обработки ошибок при создании объекта.

Представим, что у нас есть класс *Divider*, который имеет функцию *divide*, она принимает аргумент — число, на которое необходимо разделить.