# bad_alloc и new
В настоящее время в C++ проблемы, возникающие во время выделения памяти с помощью операции *new*, обрабатываются путем генерации в new исключения *bad_alloc*. Заголовочный файл *< new >* включает объявление класса *bad_alloc*, открыто унаследованного от класса *exception*. Правда, раньше операция new возвращала нулевой указатель *nullptr*, если не могла выделить запрошенный объем памяти.

Если исключение перехвачено, программа выводит зависящее от реализации сообщение, которое возвращается унаследованным виртуальным методом *what()*:

_CODE HERE_

В данном примере при попытки выделения 1192 Гб памяти генерируется исключение, которое мы благополучно обрабатываем:

<code>bad_alloc caught!                                        
std::bad_alloc</code>

На сегодня данный подход считается более безопасным и правильным, чем ожидание возврата *nullptr*. Мы явно в блоке try пробуем выделить память, если попытка не оказалось успешной, мы генерируем исключение и обрабатываем его там, где считаем необходимым.

Существует ещё старая версия new, которая не генерирует исключения. Чтобы вызвать её, необходимо явно указать:

<code>Object* obj = new(nothrow) Object();</code>

Однако такой подход считается устаревшим и принято обрабатывать исключения с помощью *bad_alloc*.